nowo_twig_inspector_template_link:
  path: /_template/{template}
  requirements:
    template: ".+"
  defaults:
    _controller: nowo_twig_inspector.controller.open_template
    line: 1
  options:
    frontend: true

